apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
  namespace: exercise-07
spec: 
  clusterIP: None
  selector: 
    app: nginx
  ports:
    - port: 80
      name: web
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: exercise-07
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "nginx"
  replicas: 3
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: nginx:1.28
          volumeMounts:
          - name: mysql-storage
            mountPath: /usr/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Mi

